begin;

alter table public.portal_inventario add column if not exists inservivel_em timestamptz;
alter table public.portal_inventario add column if not exists inservivel_por uuid;

create table if not exists public.portal_transferencias_inventario (
  id uuid primary key default gen_random_uuid(), inventario_origem_id uuid not null unique,
  unidade_origem_id bigint not null, unidade_destino_id bigint not null,
  item jsonb not null, status text not null default 'PENDENTE' check(status in ('PENDENTE','RECEBIDA','CANCELADA')),
  enviado_por uuid not null, enviado_em timestamptz not null default now(),
  recebido_por uuid, recebido_em timestamptz, sala_destino_id uuid
);
alter table public.portal_transferencias_inventario enable row level security;
grant select,insert,update on public.portal_transferencias_inventario to authenticated;
create policy transferencias_select on public.portal_transferencias_inventario for select to authenticated using (private.portal_unidade_aprovada(unidade_origem_id) or private.portal_unidade_aprovada(unidade_destino_id) or private.portal_pode_administrar());
create policy transferencias_insert on public.portal_transferencias_inventario for insert to authenticated with check (private.portal_unidade_aprovada(unidade_origem_id) and enviado_por=auth.uid());
create policy transferencias_update on public.portal_transferencias_inventario for update to authenticated using (private.portal_unidade_aprovada(unidade_destino_id) or private.portal_pode_administrar()) with check (private.portal_unidade_aprovada(unidade_destino_id) or private.portal_pode_administrar());

create or replace function public.portal_mover_inventario_sala(p_item_id uuid,p_sala_id uuid) returns public.portal_inventario language plpgsql security invoker set search_path=public,pg_temp as $$ declare r public.portal_inventario; begin update public.portal_inventario i set sala_id=p_sala_id,atualizado_por=auth.uid() where i.id=p_item_id and i.ativo and exists(select 1 from public.portal_salas s where s.id=p_sala_id and s.unidade_id=i.unidade_id and s.ativo) returning i.* into r; if not found then raise exception 'Não foi possível mover este item para a sala selecionada.'; end if; return r; end $$;
create or replace function public.portal_marcar_inventario_inservivel(p_item_id uuid) returns public.portal_inventario language plpgsql security invoker set search_path=public,pg_temp as $$ declare r public.portal_inventario; begin update public.portal_inventario set ativo=false,estado='INSERVIVEL',inservivel_em=now(),inservivel_por=auth.uid(),atualizado_por=auth.uid() where id=p_item_id and ativo returning * into r; if not found then raise exception 'Item não está disponível.'; end if; return r; end $$;
create or replace function public.portal_transferir_inventario(p_item_id uuid,p_unidade_destino bigint) returns public.portal_transferencias_inventario language plpgsql security invoker set search_path=public,pg_temp as $$ declare i public.portal_inventario; t public.portal_transferencias_inventario; begin if p_unidade_destino is null then raise exception 'Selecione a unidade de destino.'; end if; select * into i from public.portal_inventario where id=p_item_id and ativo for update; if not found or i.unidade_id=p_unidade_destino then raise exception 'Transferência inválida.'; end if; update public.portal_inventario set ativo=false,atualizado_por=auth.uid() where id=i.id; insert into public.portal_transferencias_inventario(inventario_origem_id,unidade_origem_id,unidade_destino_id,item,enviado_por) values(i.id,i.unidade_id,p_unidade_destino,to_jsonb(i),auth.uid()) returning * into t; return t; end $$;
create or replace function public.portal_receber_transferencia(p_transferencia_id uuid,p_sala_id uuid) returns public.portal_inventario language plpgsql security invoker set search_path=public,pg_temp as $$ declare t public.portal_transferencias_inventario; r public.portal_inventario; begin select * into t from public.portal_transferencias_inventario where id=p_transferencia_id and status='PENDENTE' for update; if not found or not exists(select 1 from public.portal_salas s where s.id=p_sala_id and s.unidade_id=t.unidade_destino_id and s.ativo) then raise exception 'Transferência ou sala inválida.'; end if; insert into public.portal_inventario(unidade_id,sala_id,item_nome,categoria,quantidade,patrimonio,numero_serie,marca,modelo,estado,observacoes,criado_por,atualizado_por) values(t.unidade_destino_id,p_sala_id,t.item->>'item_nome',t.item->>'categoria',1,t.item->>'patrimonio',t.item->>'numero_serie',t.item->>'marca',t.item->>'modelo',coalesce(t.item->>'estado','BOM'),t.item->>'observacoes',auth.uid(),auth.uid()) returning * into r; update public.portal_transferencias_inventario set status='RECEBIDA',recebido_por=auth.uid(),recebido_em=now(),sala_destino_id=p_sala_id where id=t.id; return r; end $$;
revoke all on function public.portal_mover_inventario_sala(uuid,uuid),public.portal_marcar_inventario_inservivel(uuid),public.portal_transferir_inventario(uuid,bigint),public.portal_receber_transferencia(uuid,uuid) from public;
grant execute on function public.portal_mover_inventario_sala(uuid,uuid),public.portal_marcar_inventario_inservivel(uuid),public.portal_transferir_inventario(uuid,bigint),public.portal_receber_transferencia(uuid,uuid) to authenticated;
commit;
